package com.example.popla.gorkhavidyutpowerpay.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BILL_DETAILS".
 */
@Entity
public class Bill_details {

    @Id(autoincrement = true)
    private Long Bill_id;
    private String k_no;
    private String current_read;
    private java.util.Date generated_date;
    private String due_date;
    private String paid_by;
    private Long TimeStamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Bill_details() {
    }

    public Bill_details(Long Bill_id) {
        this.Bill_id = Bill_id;
    }

    @Generated
    public Bill_details(Long Bill_id, String k_no, String current_read, java.util.Date generated_date, String due_date, String paid_by, Long TimeStamp) {
        this.Bill_id = Bill_id;
        this.k_no = k_no;
        this.current_read = current_read;
        this.generated_date = generated_date;
        this.due_date = due_date;
        this.paid_by = paid_by;
        this.TimeStamp = TimeStamp;
    }

    public Long getBill_id() {
        return Bill_id;
    }

    public void setBill_id(Long Bill_id) {
        this.Bill_id = Bill_id;
    }

    public String getK_no() {
        return k_no;
    }

    public void setK_no(String k_no) {
        this.k_no = k_no;
    }

    public String getCurrent_read() {
        return current_read;
    }

    public void setCurrent_read(String current_read) {
        this.current_read = current_read;
    }

    public java.util.Date getGenerated_date() {
        return generated_date;
    }

    public void setGenerated_date(java.util.Date generated_date) {
        this.generated_date = generated_date;
    }

    public String getDue_date() {
        return due_date;
    }

    public void setDue_date(String due_date) {
        this.due_date = due_date;
    }

    public String getPaid_by() {
        return paid_by;
    }

    public void setPaid_by(String paid_by) {
        this.paid_by = paid_by;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
