package com.example.popla.gorkhavidyutpowerpay.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BILL_DETAILS".
 */
@Entity
public class Bill_details {

    @Id(autoincrement = true)
    private Long Bill_id;
    private String k_no;
    private String previous_read;
    private String current_read;
    private java.util.Date generated_date;
    private String paid_by;
    private String receipt_no;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Bill_details() {
    }

    public Bill_details(Long Bill_id) {
        this.Bill_id = Bill_id;
    }

    @Generated
    public Bill_details(Long Bill_id, String k_no, String previous_read, String current_read, java.util.Date generated_date, String paid_by, String receipt_no) {
        this.Bill_id = Bill_id;
        this.k_no = k_no;
        this.previous_read = previous_read;
        this.current_read = current_read;
        this.generated_date = generated_date;
        this.paid_by = paid_by;
        this.receipt_no = receipt_no;
    }

    public Long getBill_id() {
        return Bill_id;
    }

    public void setBill_id(Long Bill_id) {
        this.Bill_id = Bill_id;
    }

    public String getK_no() {
        return k_no;
    }

    public void setK_no(String k_no) {
        this.k_no = k_no;
    }

    public String getPrevious_read() {
        return previous_read;
    }

    public void setPrevious_read(String previous_read) {
        this.previous_read = previous_read;
    }

    public String getCurrent_read() {
        return current_read;
    }

    public void setCurrent_read(String current_read) {
        this.current_read = current_read;
    }

    public java.util.Date getGenerated_date() {
        return generated_date;
    }

    public void setGenerated_date(java.util.Date generated_date) {
        this.generated_date = generated_date;
    }

    public String getPaid_by() {
        return paid_by;
    }

    public void setPaid_by(String paid_by) {
        this.paid_by = paid_by;
    }

    public String getReceipt_no() {
        return receipt_no;
    }

    public void setReceipt_no(String receipt_no) {
        this.receipt_no = receipt_no;
    }

    /*public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }*/



    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
