package com.example.popla.gorkhavidyutpowerpay.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "COMPLAINT__DETAILS".
 */
@Entity
public class Complaint_Details {

    @Id(autoincrement = true)
    private Long Complaint_No;
    private String Comp_K_No;
    private String Comp_Login_Id;
    private String Comp_Date;
    private String Comp_Msg;
    private String Comp_Status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Complaint_Details() {
    }

    public Complaint_Details(Long Complaint_No) {
        this.Complaint_No = Complaint_No;
    }

    @Generated
    public Complaint_Details(Long Complaint_No, String Comp_K_No, String Comp_Login_Id, String Comp_Date, String Comp_Msg, String Comp_Status) {
        this.Complaint_No = Complaint_No;
        this.Comp_K_No = Comp_K_No;
        this.Comp_Login_Id = Comp_Login_Id;
        this.Comp_Date = Comp_Date;
        this.Comp_Msg = Comp_Msg;
        this.Comp_Status = Comp_Status;
    }

    public Long getComplaint_No() {
        return Complaint_No;
    }

    public void setComplaint_No(Long Complaint_No) {
        this.Complaint_No = Complaint_No;
    }

    public String getComp_K_No() {
        return Comp_K_No;
    }

    public void setComp_K_No(String Comp_K_No) {
        this.Comp_K_No = Comp_K_No;
    }

    public String getComp_Login_Id() {
        return Comp_Login_Id;
    }

    public void setComp_Login_Id(String Comp_Login_Id) {
        this.Comp_Login_Id = Comp_Login_Id;
    }

    public String getComp_Date() {
        return Comp_Date;
    }

    public void setComp_Date(String Comp_Date) {
        this.Comp_Date = Comp_Date;
    }

    public String getComp_Msg() {
        return Comp_Msg;
    }

    public void setComp_Msg(String Comp_Msg) {
        this.Comp_Msg = Comp_Msg;
    }

    public String getComp_Status() {
        return Comp_Status;
    }

    public void setComp_Status(String Comp_Status) {
        this.Comp_Status = Comp_Status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
