package com.example.popla.gorkhavidyutpowerpay.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.popla.gorkhavidyutpowerpay.db.User;
import com.example.popla.gorkhavidyutpowerpay.db.Employee;
import com.example.popla.gorkhavidyutpowerpay.db.Register;
import com.example.popla.gorkhavidyutpowerpay.db.New_Connection;
import com.example.popla.gorkhavidyutpowerpay.db.Complaint_Details;

import com.example.popla.gorkhavidyutpowerpay.db.UserDao;
import com.example.popla.gorkhavidyutpowerpay.db.EmployeeDao;
import com.example.popla.gorkhavidyutpowerpay.db.RegisterDao;
import com.example.popla.gorkhavidyutpowerpay.db.New_ConnectionDao;
import com.example.popla.gorkhavidyutpowerpay.db.Complaint_DetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig employeeDaoConfig;
    private final DaoConfig registerDaoConfig;
    private final DaoConfig new_ConnectionDaoConfig;
    private final DaoConfig complaint_DetailsDaoConfig;

    private final UserDao userDao;
    private final EmployeeDao employeeDao;
    private final RegisterDao registerDao;
    private final New_ConnectionDao new_ConnectionDao;
    private final Complaint_DetailsDao complaint_DetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        employeeDaoConfig = daoConfigMap.get(EmployeeDao.class).clone();
        employeeDaoConfig.initIdentityScope(type);

        registerDaoConfig = daoConfigMap.get(RegisterDao.class).clone();
        registerDaoConfig.initIdentityScope(type);

        new_ConnectionDaoConfig = daoConfigMap.get(New_ConnectionDao.class).clone();
        new_ConnectionDaoConfig.initIdentityScope(type);

        complaint_DetailsDaoConfig = daoConfigMap.get(Complaint_DetailsDao.class).clone();
        complaint_DetailsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        employeeDao = new EmployeeDao(employeeDaoConfig, this);
        registerDao = new RegisterDao(registerDaoConfig, this);
        new_ConnectionDao = new New_ConnectionDao(new_ConnectionDaoConfig, this);
        complaint_DetailsDao = new Complaint_DetailsDao(complaint_DetailsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Employee.class, employeeDao);
        registerDao(Register.class, registerDao);
        registerDao(New_Connection.class, new_ConnectionDao);
        registerDao(Complaint_Details.class, complaint_DetailsDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        employeeDaoConfig.clearIdentityScope();
        registerDaoConfig.clearIdentityScope();
        new_ConnectionDaoConfig.clearIdentityScope();
        complaint_DetailsDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public EmployeeDao getEmployeeDao() {
        return employeeDao;
    }

    public RegisterDao getRegisterDao() {
        return registerDao;
    }

    public New_ConnectionDao getNew_ConnectionDao() {
        return new_ConnectionDao;
    }

    public Complaint_DetailsDao getComplaint_DetailsDao() {
        return complaint_DetailsDao;
    }

}
