package com.example.popla.gorkhavidyutpowerpay.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EMPLOYEE".
 */
@Entity
public class Employee {

    @Id(autoincrement = true)
    private Long emp_id;
    private String emp_name;
    private String emp_email_id;
    private String emp_mobile;
    private String emp_age;
    private String emp_designation;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Employee() {
    }

    public Employee(Long emp_id) {
        this.emp_id = emp_id;
    }

    @Generated
    public Employee(Long emp_id, String emp_name, String emp_email_id, String emp_mobile, String emp_age, String emp_designation) {
        this.emp_id = emp_id;
        this.emp_name = emp_name;
        this.emp_email_id = emp_email_id;
        this.emp_mobile = emp_mobile;
        this.emp_age = emp_age;
        this.emp_designation = emp_designation;
    }

    public Long getEmp_id() {
        return emp_id;
    }

    public void setEmp_id(Long emp_id) {
        this.emp_id = emp_id;
    }

    public String getEmp_name() {
        return emp_name;
    }

    public void setEmp_name(String emp_name) {
        this.emp_name = emp_name;
    }

    public String getEmp_email_id() {
        return emp_email_id;
    }

    public void setEmp_email_id(String emp_email_id) {
        this.emp_email_id = emp_email_id;
    }

    public String getEmp_mobile() {
        return emp_mobile;
    }

    public void setEmp_mobile(String emp_mobile) {
        this.emp_mobile = emp_mobile;
    }

    public String getEmp_age() {
        return emp_age;
    }

    public void setEmp_age(String emp_age) {
        this.emp_age = emp_age;
    }

    public String getEmp_designation() {
        return emp_designation;
    }

    public void setEmp_designation(String emp_designation) {
        this.emp_designation = emp_designation;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
