package com.example.popla.gorkhavidyutpowerpay.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "NEW__CONNECTION".
 */
@Entity
public class New_Connection {

    @Id(autoincrement = true)
    private Long application_id;
    private String applicant_name;
    private String applicant_fname;
    private String applicant_DOB;
    private String applicant_occupaion;
    private String applicant_area;
    private String applicant_landmark;
    private String applicant_city;
    private String applicant_pincode;
    private String applicant_contype;
    private Float applicant_Psize;
    private Float applicant_covereda;
    private Float applicant_reqKV;
    private String applicant_pos;
    private String applicant_aadhar;
    private java.util.Date submit_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public New_Connection() {
    }

    public New_Connection(Long application_id) {
        this.application_id = application_id;
    }

    @Generated
    public New_Connection(Long application_id, String applicant_name, String applicant_fname, String applicant_DOB, String applicant_occupaion, String applicant_area, String applicant_landmark, String applicant_city, String applicant_pincode, String applicant_contype, Float applicant_Psize, Float applicant_covereda, Float applicant_reqKV, String applicant_pos, String applicant_aadhar, java.util.Date submit_date) {
        this.application_id = application_id;
        this.applicant_name = applicant_name;
        this.applicant_fname = applicant_fname;
        this.applicant_DOB = applicant_DOB;
        this.applicant_occupaion = applicant_occupaion;
        this.applicant_area = applicant_area;
        this.applicant_landmark = applicant_landmark;
        this.applicant_city = applicant_city;
        this.applicant_pincode = applicant_pincode;
        this.applicant_contype = applicant_contype;
        this.applicant_Psize = applicant_Psize;
        this.applicant_covereda = applicant_covereda;
        this.applicant_reqKV = applicant_reqKV;
        this.applicant_pos = applicant_pos;
        this.applicant_aadhar = applicant_aadhar;
        this.submit_date = submit_date;
    }

    public Long getApplication_id() {
        return application_id;
    }

    public void setApplication_id(Long application_id) {
        this.application_id = application_id;
    }

    public String getApplicant_name() {
        return applicant_name;
    }

    public void setApplicant_name(String applicant_name) {
        this.applicant_name = applicant_name;
    }

    public String getApplicant_fname() {
        return applicant_fname;
    }

    public void setApplicant_fname(String applicant_fname) {
        this.applicant_fname = applicant_fname;
    }

    public String getApplicant_DOB() {
        return applicant_DOB;
    }

    public void setApplicant_DOB(String applicant_DOB) {
        this.applicant_DOB = applicant_DOB;
    }

    public String getApplicant_occupaion() {
        return applicant_occupaion;
    }

    public void setApplicant_occupaion(String applicant_occupaion) {
        this.applicant_occupaion = applicant_occupaion;
    }

    public String getApplicant_area() {
        return applicant_area;
    }

    public void setApplicant_area(String applicant_area) {
        this.applicant_area = applicant_area;
    }

    public String getApplicant_landmark() {
        return applicant_landmark;
    }

    public void setApplicant_landmark(String applicant_landmark) {
        this.applicant_landmark = applicant_landmark;
    }

    public String getApplicant_city() {
        return applicant_city;
    }

    public void setApplicant_city(String applicant_city) {
        this.applicant_city = applicant_city;
    }

    public String getApplicant_pincode() {
        return applicant_pincode;
    }

    public void setApplicant_pincode(String applicant_pincode) {
        this.applicant_pincode = applicant_pincode;
    }

    public String getApplicant_contype() {
        return applicant_contype;
    }

    public void setApplicant_contype(String applicant_contype) {
        this.applicant_contype = applicant_contype;
    }

    public Float getApplicant_Psize() {
        return applicant_Psize;
    }

    public void setApplicant_Psize(Float applicant_Psize) {
        this.applicant_Psize = applicant_Psize;
    }

    public Float getApplicant_covereda() {
        return applicant_covereda;
    }

    public void setApplicant_covereda(Float applicant_covereda) {
        this.applicant_covereda = applicant_covereda;
    }

    public Float getApplicant_reqKV() {
        return applicant_reqKV;
    }

    public void setApplicant_reqKV(Float applicant_reqKV) {
        this.applicant_reqKV = applicant_reqKV;
    }

    public String getApplicant_pos() {
        return applicant_pos;
    }

    public void setApplicant_pos(String applicant_pos) {
        this.applicant_pos = applicant_pos;
    }

    public String getApplicant_aadhar() {
        return applicant_aadhar;
    }

    public void setApplicant_aadhar(String applicant_aadhar) {
        this.applicant_aadhar = applicant_aadhar;
    }

    public java.util.Date getSubmit_date() {
        return submit_date;
    }

    public void setSubmit_date(java.util.Date submit_date) {
        this.submit_date = submit_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
